### ISSUE TITLE
2.4.1 As a user, I want to receive a score when I complete a level so that I feel encouraged to do my best.

### ISSUE THREAD

**Issue by em135** [Xitric/AR-Programming#34]
### Tasks
- [x] 2.4.1.1 Add a score indicator in the form of stars or coins to completed levels in the level select view.
- [x] 2.4.1.2 Create a column in Core Data for storing the user’s score on a level.

### Acceptance criteria
- Award the user when the goal quantity is met in a quantity level.
- Award the user when all the right items have been collected in a collection level.
- Award the user when all objects have been put in the right places in an organizing level.
- Display the user's score on all completed levels.
- Display the user's total amount of coins or stars.
- The user is awarded only once for each obtainable star or coin when completing a level.
- Users are able to explain how well they did on a level they just completed within 20 seconds of being queried.

**Comment by Xitric** [comment]
Since Levels should not know about the ProgramEditor, we should probably inject a ScoreCalculator into a level after it has been created (loaded from json). Then a separate class can calculate scores.
